name: Dev Build

on:
  push:
    paths:
      - "**.java"
      - "**.gradle"
      - ".github/workflows/ci.yml"
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      # Fabric 1.21-1.20.5
      - name: Upload Artifact (Fabric 1.21-1.20.5)
        uses: actions/upload-artifact@v4
        with:
          name: 'urlimg Fabric 1.21-1.20.5'
          path: |
            urlimg-fabric/urlimg-fabric-1.21-1.20.5/build/libs/**.jar
      # Fabric 1.20.4-1.20.2
      - name: Upload Artifact (Fabric 1.20.4-1.20.2)
        uses: actions/upload-artifact@v4
        with:
          name: 'urlimg Fabric 1.20.4-1.20.2'
          path: |
            urlimg-fabric/urlimg-fabric-1.20.4-1.20.2/build/libs/**.jar
      # Fabric 1.20.1-1.20
      - name: Upload Artifact (Fabric 1.20.1-1.20)
        uses: actions/upload-artifact@v4
        with:
          name: 'urlimg Fabric 1.20.1-1.20'
          path: |
            urlimg-fabric/urlimg-fabric-1.20.1-1.20/build/libs/**.jar
      # Fabric 1.19.4
      - name: Upload Artifact (Fabric 1.19.4)
        uses: actions/upload-artifact@v4
        with:
          name: 'urlimg Fabric 1.19.4'
          path: |
            urlimg-fabric/urlimg-fabric-1.19.4/build/libs/**.jar
      # Forge 1.16.5
      - name: Upload Artifact (Forge 1.16.5)
        uses: actions/upload-artifact@v4
        with:
          name: 'urlimg Forge 1.16.5'
          path: |
            urlimg-forge/urlimg-forge-1.16.5/build/libs/**.jar