name: Stable Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            urlimg-fabric/urlimg-fabric-1.21-1.20.5/build/libs/**.jar
            urlimg-fabric/urlimg-fabric-1.20.4-1.20.2/build/libs/**.jar
            urlimg-fabric/urlimg-fabric-1.20.1-1.20/build/libs/**.jar
            urlimg-fabric/urlimg-fabric-1.19.4/build/libs/**.jar
            urlimg-forge/urlimg-forge-1.16.5/build/libs/**.jar
            urlimg-forge/urlimg-forge-1.20.1/build/libs/**.jar